### ISSUE TITLE
cannot "make"

### ISSUE THREAD

**Issue by pebaudhi** [ibara/chargend#1]
Using Ubuntu MATE  not sure what version I can't seem to find what version of Ubuntu MATE.
cc -O2 -pipe -Wall -Wextra -o chargend chargend.c
chargend.c: In function ‘sendtcp’:
chargend.c:79:4: warning: implicit declaration of function ‘strlcpy’ [-Wimplicit-function-declaration]
    strlcpy(cbuf, characters[i++], sizeof(cbuf));
    ^~~~~~~
chargend.c:80:4: warning: implicit declaration of function ‘strlcat’ [-Wimplicit-function-declaration]
    strlcat(cbuf, "\n", sizeof(cbuf));
    ^~~~~~~
chargend.c: In function ‘main’:
chargend.c:275:6: warning: implicit declaration of function ‘setgroups’ [-Wimplicit-function-declaration]
  if (setgroups(1, &pw->pw_gid) ||
      ^~~~~~~~~
chargend.c:276:6: warning: implicit declaration of function ‘setresgid’ [-Wimplicit-function-declaration]
      setresgid(pw->pw_gid, pw->pw_gid, pw->pw_gid) ||
      ^~~~~~~~~
chargend.c:277:6: warning: implicit declaration of function ‘setresuid’ [-Wimplicit-function-declaration]
      setresuid(pw->pw_uid, pw->pw_uid, pw->pw_uid)) {
      ^~~~~~~~~
/tmp/ccISsKKJ.o: In function `main':
chargend.c:(.text.startup+0x609): undefined reference to `strlcpy'
chargend.c:(.text.startup+0x61f): undefined reference to `strlcat'
chargend.c:(.text.startup+0x71c): undefined reference to `strlcpy'
chargend.c:(.text.startup+0x735): undefined reference to `strlcat'
collect2: error: ld returned 1 exit status
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by ibara** [comment]
glibc does not provide strlcat and strlcpy. You will have to provide those functions yourself for the time being until glibc becomes a complete C library.
